[project]
name = "mlb-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash>=3.3.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]
